home:
    path: /
    controller: App\Controller\DefaultController::home

email:
    path: /send-an-email
    controller: App\Controller\EmailController::email

blog:
    path: /blog-posts
    controller: App\Controller\BlogPostController::blog